### ISSUE TITLE
Sitemap button disabled

### ISSUE THREAD

**Issue by kosie99** [alkacon/opencms-docker#18]
I am using the 11.02 docker image and it works great, but the sitemap button is disabled and I have no idea how to enable it. The documentation mentions opening the sitemap editor to create a sitemap,  but obviously I cannot do that with it being greyed out.
Is that someting specific with this docker image?

If not, can I please be pointed to the documentation where enabling the sitemap is discussed?

Thanks!
Kosie

**Comment by alkacon-jGraf** [comment]
Hi Kosie,
this is certainly not a Docker related issue.
If the sitemap editor appears disabled this is usually because you are either in the root folder of your OpenCms installation or you did create an empty website, which has no "Sitemap Content Folder" and no "Sitemap configuration file" yet.
If you have further questions about this, it would be better to ask them in the OpenCms mailing list.
Best
Jochen
